- id: static-analysis
  name: static analysis
  description: Static analysis linter.
  entry: static-analysis
  language: python
  types: [python]

- id: make-api-doc
  name: make api documentation
  description: creates an api.rst file for readthedocs
  entry: make-api-doc
  language: python
  types: [python]

- id: remove-empty-lines
  name: remove empty lines
  description: Remove empty lines.
  entry: remove-empty-lines
  files: \.(csv)$
