- id: static-analysis
  name: static analysis
  description: Static analysis linter.
  entry: static-analysis
  language: python
  types: [python]

- id: make-api-doc
  name: make api documentation
  description: creates an api.rst file for readthedocs
  entry: make-api-doc
  language: python
  types: [python]

- id: format-csv
  name: format CSV files
  description: Format CSV files (remove empty lines + sort).
  entry: format-csv
  language: python
  files: triplets\.csv$

- id: format-triplets
  name: format triplets files
  description: Format CSV files (remove empty lines + sort).
  entry: format-triplets
  language: python
  files: triplets\.csv$
