- id: static-analysis
  name: static analysis
  description: Static analysis linter.
  entry: static-analysis
  language: python
  types: [python]

- id: make-api-doc
  name: make api documentation
  description: creates an api.rst file for readthedocs
  entry: make-api-doc
  language: python
  types: [python]

- id: format-csv
  name: format CSV files
  description: Format CSV files (remove empty lines + sort).
  entry: format-csv
  language: python
  files: triplets\.csv$

- id: format-assistant-configuration
  name: format assistant_configuration.json files
  description: Format Json files (sort configuration).
  entry: format-assistant-configuration
  language: python
  files: assistant_configuration\.json$

- id: validate-triplets
  name: validate triplets files
  description: Validate triplets files format (no duplicate references).
  entry: validate-triplets
  language: python
  files: triplets\.csv$

- id: hyro-pre-commit
  name: Hyro standard hooks
  language: script
  entry: ./run-hyro-hooks
  verbose: true