#!/usr/bin/env python
import os
import sys

HERE = os.path.dirname(os.path.realpath(__file__))


def main():
    cfg = os.path.join(HERE, "hyro-hooks.yaml")
    cmd = ["pre-commit", "run", "--config", cfg, "--files"] + sys.argv[1:]
    env = os.environ | {"SKIP": "mypy"} if "nlu-runtime" in os.getcwd() else os.environ

    os.execvpe(cmd[0], cmd, env)


if __name__ == "__main__":
    exit(main())
